controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.2 #0.5
  min_vel_x: -0.5 #0.01
  max_vel_theta: 1.57 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  sim_time: 4.0

  vx_samples: 20.0
  vtheta_samples: 40.0

  meter_scoring: true

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false
